### ISSUE TITLE
Divide By Zero Error for MLB

### ISSUE THREAD

**Issue by user2745** [AthleteX-DAO/ax-DB#14]
Traceback (most recent call last):
  File "/home/ubuntu/ax-DB/./GetMLBAthleteData.py", line 91, in <module>
    price = computePrice(athlete, lgWeighedOnBase, sumPlateAppearances)
  File "/home/ubuntu/ax-DB/./GetMLBAthleteData.py", line 48, in computePrice
    FieldingRuns = ((athlete_data['Errors'] * (-10)) / games)
ZeroDivisionError: float division by zero

**Comment by user2745** [comment]
This is resolved
